### ISSUE TITLE
Wireframes and user flow

### ISSUE THREAD

**Issue by laurencecnerual** [cc-pet-sitter/frontend#1]

**Comment by vicentbe10** [comment]
Work in progress on the User Story Mapping to give clarity on the flows
https://miro.com/app/board/uXjVLDucRx0=/?share_link_id=166221177951

**Comment by vicentbe10** [comment]
Updated the Miro dashboard.

Additionally, I thought that we could require a little bit more of context (myself included) than just the Miro dashboard. 
So I did a bit of research on the web and with Mr chatGPT about the best way to do it and I drafted this document.
https://docs.google.com/document/d/1ZI3R7TBBJMDC8cO8r7TJDZY__uvMOCgXnTaR9Of_Oqs/edit?usp=sharing

I can explain tomorrow.
Anyway, I hope it's useful to align and to have a better departing point to start coding.

**Comment by vicentbe10** [comment]
Progress on the wireframe and added some additional screens for the dashboard
https://miro.com/app/board/uXjVLDucRx0=/?share_link_id=166221177951

Balsamiq free trial is finishing so let me add here a pdf of the current stage.
[PetSitter.pdf](https://github.com/user-attachments/files/17817458/PetSitter.pdf)
